version: '3.1'

services:
  hw0:
    image: YOUR_ZK_IMAGE
    hostname: hw0
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      # Uncomment for pass environment variable 
      # ENV_NAME: VALUE
      ZOO_SERVERS: server.1=hw0:2888:3888;2181 server.2=hw1:2888:3888;2181
    volumes:       
      - YOUR_ZOOKEEPER_REPO:/apache-zookeeper-3.6.1-bin/
  hw1:
    image: YOUR_ZK_IMAGE
    hostname: hw1
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      # Uncomment for pass environment variable 
      # ENV_NAME: VALUE
      ZOO_SERVERS: server.1=hw0:2888:3888;2181 server.2=hw1:2888:3888;2181
    volumes:
      - YOUR_ZOOKEEPER_REPO:/apache-zookeeper-3.6.1-bin/

